# Generated by Django 4.0.4 on 2022-06-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmedia',
            name='organization',
            field=models.ForeignKey(choices=[('ua', 'Ukrainian'), ('en', 'English')], on_delete=django.db.models.deletion.CASCADE, to='booking.organization'),
        ),
    ]
