# Generated by Django 4.0.4 on 2022-06-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_organizationmedia_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationdescription',
            name='language',
            field=models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationmedia',
            name='media',
            field=models.ImageField(upload_to='organization/'),
        ),
        migrations.AlterField(
            model_name='organizationmedia',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationdescription',
            unique_together={('organization', 'language')},
        ),
    ]
