# Generated by Django 4.0.4 on 2022-06-21 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_alter_organization_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('st_3', 'Standart 3'), ('st_4', 'Standart 4')], max_length=4)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('on_hold', 'On hold'), ('canceled', 'Canceled')], default='on_hold', max_length=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.calendar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.order')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_data', models.DateField(help_text='Data from price actual', verbose_name='Actual data')),
                ('category', models.CharField(choices=[('st_3', 'Standart 3'), ('st_4', 'Standart 4')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.organization')),
            ],
        ),
    ]
