# Generated by Django 4.0.4 on 2022-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_apartment_calendar_order_orderdata_apartmentprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['name'], 'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='data',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
    ]
