# Generated by Django 4.0.4 on 2022-06-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_apartment_options_alter_calendar_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.apartment')),
                ('calendar_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.calendar')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.order')),
            ],
            options={
                'ordering': ['apartment', 'calendar_data'],
                'unique_together': {('calendar_data', 'apartment')},
            },
        ),
    ]
