# Generated by Django 4.0.4 on 2022-06-27 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_reservationmatrix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmatrix',
            options={'ordering': ['apartment', 'data']},
        ),
        migrations.AlterUniqueTogether(
            name='reservationmatrix',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='date',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 14, 53, 16, 442968), verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='reservationmatrix',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 14, 53, 16, 439940), verbose_name='Data'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationmatrix',
            unique_together={('data', 'apartment')},
        ),
        migrations.RemoveField(
            model_name='reservationmatrix',
            name='calendar_data',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
