# Generated by Django 4.0.4 on 2022-06-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_user_phone_number_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
