# Generated by Django 4.0.4 on 2022-07-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservation_without_payment',
            field=models.BooleanField(default=False),
        ),
    ]
